const MESSAGES_FROM_CLIENT_TO_SERVER = "MESSAGES_FROM_CLIENT_TO_SERVER";
const MESSAGES_FROM_SERVER_TO_CLIENT = "MESSAGES_FROM_SERVER_TO_CLIENT";

module.exports = {
  MESSAGES_FROM_CLIENT_TO_SERVER,
  MESSAGES_FROM_SERVER_TO_CLIENT,
};
